import { StyleSheet } from 'react-native';
import { chartCardStyle } from '@theme/chartTheme';
import { colors, spacing, typography } from '@theme';

const safeTypography = typography || {
  fonts: {
    secondaryMedium: 'Rajdhani-Medium',
    mono: 'JetBrainsMono-Regular',
    primarySemiBold: 'Orbitron-SemiBold',
    primaryBold: 'Orbitron-Bold',
    secondarySemiBold: 'Rajdhani-SemiBold',
    secondary: 'Rajdhani-Regular',
  },
  weights: { medium: '500', semiBold: '600', bold: '700' },
  sizes: { xs: 11, sm: 14, xxl: 48 },
};
const safeColors = colors || { primary: '#FFD700', error: '#EF4444', success: '#10B981', textSecondary: '#B8BCC8' };
const safeSpacing = spacing || { xs: 4, sm: 8, md: 16, lg: 24, xl: 32 };

export { safeTypography, safeColors, safeSpacing };

export const itemDetailStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#121212',
    width: '100%',
    height: '100%',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    padding: safeSpacing.md,
    paddingBottom: safeSpacing.sm,
    zIndex: 10,
  },
  closeButton: {
    paddingVertical: safeSpacing.xs || 4,
    paddingHorizontal: safeSpacing.md || 16,
  },
  closeButtonText: {
    fontSize: safeTypography.sizes.xs || 11,
    fontFamily: safeTypography.fonts.secondarySemiBold || 'Rajdhani-SemiBold',
    color: safeColors.textSecondary || '#B8BCC8',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  content: { flex: 1 },
  headerCompact: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    paddingHorizontal: safeSpacing.lg,
    paddingTop: safeSpacing.md,
    paddingBottom: safeSpacing.md,
    marginBottom: safeSpacing.md,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.05)',
  },
  headerLeft: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    flex: 1,
  },
  headerTitle: {
    fontSize: 18,
    fontFamily: safeTypography.fonts.primaryBold,
    fontWeight: safeTypography.weights.bold,
    lineHeight: 22,
  },
  headerWeaponName: { color: '#FFFFFF' },
  headerSeparator: { color: '#d4c291' },
  headerSkinName: { color: '#d4c291' },
  headerCondition: {
    fontSize: 10,
    fontFamily: safeTypography.fonts.secondaryMedium,
    color: '#6B7280',
    marginTop: 2,
    letterSpacing: 3.2,
    fontWeight: safeTypography.weights.medium,
    textTransform: 'uppercase',
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: safeSpacing.sm,
    marginLeft: safeSpacing.md,
  },
  headerPrice: {
    fontSize: 20,
    fontFamily: safeTypography.fonts.mono || safeTypography.fonts.primaryBold,
    fontWeight: safeTypography.weights.bold,
    color: '#d4c291',
  },
  storageUnitBadgeText: {
    fontSize: 12,
    fontFamily: safeTypography.fonts.secondary,
    color: 'rgba(180, 180, 180, 0.9)',
  },
  storageUnitBadgeNumber: {
    color: '#d4c291',
    fontFamily: safeTypography.fonts.primaryBold,
    fontWeight: safeTypography.weights.bold,
  },
  headerTrendBadge: {
    paddingHorizontal: safeSpacing.sm,
    paddingVertical: safeSpacing.xs,
    borderRadius: 4,
    borderWidth: 1,
  },
  headerTrendPositive: {
    backgroundColor: 'transparent',
    borderColor: 'rgba(16, 185, 129, 0.2)',
  },
  headerTrendNegative: {
    backgroundColor: 'transparent',
    borderColor: 'rgba(239, 68, 68, 0.2)',
  },
  headerTrendText: {
    fontSize: 12,
    fontFamily: safeTypography.fonts.primaryBold,
    fontWeight: safeTypography.weights.bold,
  },
  headerTrendTextPositive: { color: '#10b981' },
  headerTrendTextNegative: { color: '#ef4444' },
  imageContainer: {
    width: '100%',
    height: 240,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: safeSpacing.sm,
  },
  heroImage: {
    width: '100%',
    height: '100%',
    maxWidth: 300,
  },
  imagePlaceholder: {
    width: 200,
    height: 200,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: safeSpacing.sm,
  },
  placeholderText: {
    color: safeColors.textSecondary,
    fontSize: safeTypography.sizes.xxl,
  },
  assetIdRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 0,
    marginBottom: safeSpacing.md,
    paddingHorizontal: safeSpacing.md,
  },
  assetIdText: {
    fontSize: 12,
    fontFamily: safeTypography.fonts.mono,
    color: '#FFFFFF',
    textAlign: 'center',
    flexWrap: 'wrap',
  },
  assetIdLabelInline: {
    fontSize: 12,
    fontFamily: safeTypography.fonts.secondary,
    color: '#9CA3AF',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  assetIdValueInline: {
    fontSize: 12,
    fontFamily: safeTypography.fonts.mono,
    color: '#FFFFFF',
    fontWeight: safeTypography.weights.medium,
    letterSpacing: 0.5,
  },
  assetIdSeparator: {
    fontSize: 12,
    fontFamily: safeTypography.fonts.secondary,
    color: '#6B7280',
    letterSpacing: 0.5,
  },
  floatSection: {
    paddingHorizontal: safeSpacing.lg,
    paddingVertical: safeSpacing.md,
    marginBottom: safeSpacing.md,
    backgroundColor: '#1a1a1a',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(212, 194, 145, 0.15)',
  },
  floatHeader: { marginBottom: safeSpacing.md },
  floatSectionTitle: {
    fontSize: 11,
    fontFamily: safeTypography.fonts.secondaryMedium,
    color: '#d4c291',
    letterSpacing: 1.5,
    textTransform: 'uppercase',
    opacity: 0.9,
  },
  floatBarContainer: { position: 'relative', marginBottom: safeSpacing.md },
  floatBarWrapper: {
    position: 'relative',
    height: 28,
    marginBottom: safeSpacing.xs + 2,
  },
  floatBar: { width: '100%', height: 28, borderRadius: 6 },
  floatIndicatorLine: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    width: 2,
    zIndex: 5,
    transform: [{ translateX: -1 }],
  },
  floatIndicatorGlow: {
    position: 'absolute',
    top: -2,
    bottom: -2,
    left: -1,
    right: -1,
    backgroundColor: '#ffffff',
    opacity: 0.3,
    borderRadius: 1,
  },
  floatIndicatorCore: {
    flex: 1,
    backgroundColor: '#ffffff',
    borderRadius: 1,
    shadowColor: '#ffffff',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 4,
    elevation: 3,
  },
  floatMarker: {
    position: 'absolute',
    top: -8,
    zIndex: 10,
    transform: [{ translateX: -10 }],
    shadowColor: '#d4c291',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.5,
    shadowRadius: 4,
    elevation: 5,
  },
  floatConditionMarkers: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 2,
    marginTop: safeSpacing.xs,
  },
  floatConditionMarker: {
    fontSize: 9,
    fontFamily: safeTypography.fonts.secondary,
    color: '#6B7280',
    opacity: 0.5,
    letterSpacing: 0.5,
  },
  floatLabels: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: safeSpacing.lg,
  },
  floatValueContainer: { flex: 1, minWidth: 0, alignItems: 'flex-start' },
  floatLabel: {
    fontSize: 10,
    fontFamily: safeTypography.fonts.secondary,
    color: '#6B7280',
    marginBottom: safeSpacing.xs / 2,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  floatValueText: {
    fontSize: 14,
    fontFamily: safeTypography.fonts.mono,
    color: '#FFFFFF',
    fontWeight: safeTypography.weights.medium,
    letterSpacing: 0.5,
  },
  floatWearContainer: { flex: 1, alignItems: 'flex-end' },
  floatWearLabel: {
    fontSize: 10,
    fontFamily: safeTypography.fonts.secondary,
    color: '#6B7280',
    marginBottom: safeSpacing.xs / 2,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  floatWearText: {
    fontSize: 14,
    fontFamily: safeTypography.fonts.secondaryMedium,
    color: '#d4c291',
    fontWeight: safeTypography.weights.semiBold,
    textAlign: 'right',
  },
  chartSection: { padding: safeSpacing.lg },
  chartCard: {
    ...chartCardStyle,
    width: '100%',
  },
  loadingContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
  },
  emptyContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
  },
  emptyText: {
    color: safeColors.textSecondary,
    fontSize: safeTypography.sizes.sm,
    fontFamily: safeTypography.fonts.secondary,
  },
  statsSection: {
    paddingHorizontal: safeSpacing.lg,
    paddingBottom: safeSpacing.md,
  },
  statsGrid: { flexDirection: 'row', gap: safeSpacing.sm },
  statCard: {
    flex: 1,
    backgroundColor: '#1c1b19',
    borderWidth: 1,
    borderColor: 'rgba(212, 194, 145, 0.1)',
    borderRadius: 12,
    padding: safeSpacing.md,
    alignItems: 'center',
  },
  statLabel: {
    fontSize: 11,
    fontFamily: safeTypography.fonts.secondary,
    color: '#6B7280',
    marginBottom: safeSpacing.xs,
  },
  statValue: {
    fontSize: 16,
    fontFamily: safeTypography.fonts.primarySemiBold,
    color: '#d4c291',
    fontWeight: safeTypography.weights.semiBold,
  },
  analysisSection: {
    padding: safeSpacing.lg,
    paddingBottom: safeSpacing.xl,
  },
  analysisSectionTitle: {
    fontSize: 12,
    fontFamily: safeTypography.fonts.primaryBold,
    color: '#d4c291',
    fontWeight: safeTypography.weights.bold,
    textTransform: 'uppercase',
    letterSpacing: 2,
    marginBottom: safeSpacing.sm,
  },
  analysisContainer: {
    flexDirection: 'column',
    gap: safeSpacing.sm,
    marginTop: safeSpacing.md,
  },
  analysisTopRow: { flexDirection: 'row', gap: safeSpacing.sm },
  analysisCardSmall: {
    flex: 1,
    backgroundColor: '#1c1b19',
    borderWidth: 1,
    borderColor: 'rgba(212, 194, 145, 0.2)',
    borderRadius: 12,
    padding: safeSpacing.sm || 8,
    alignItems: 'center',
  },
  analysisLabel: {
    fontSize: 11,
    fontFamily: safeTypography.fonts.secondary,
    color: '#6B7280',
    marginBottom: safeSpacing.sm,
  },
  analysisValue: {
    fontSize: 18,
    fontFamily: safeTypography.fonts.primarySemiBold,
    color: '#FFFFFF',
    fontWeight: safeTypography.weights.bold,
    marginBottom: safeSpacing.xs,
  },
  analysisStatus: {
    fontSize: 11,
    fontFamily: safeTypography.fonts.secondary,
    color: '#9CA3AF',
  },
  rsiContainer: { width: '100%', marginBottom: safeSpacing.xs },
  rsiBar: {
    height: 8,
    backgroundColor: '#292524',
    borderRadius: 4,
    overflow: 'hidden',
    marginBottom: safeSpacing.xs,
  },
  rsiBarFill: { height: '100%', borderRadius: 4 },
  volatilityContainer: { width: '100%', marginBottom: safeSpacing.xs },
  volatilityBar: {
    height: 8,
    backgroundColor: '#292524',
    borderRadius: 4,
    overflow: 'hidden',
    marginBottom: safeSpacing.xs,
  },
  volatilityBarFill: { height: '100%', borderRadius: 4 },
  trendCardFullWidth: {
    backgroundColor: '#1c1b19',
    borderWidth: 1,
    borderColor: 'rgba(212, 194, 145, 0.2)',
    borderRadius: 12,
    paddingHorizontal: safeSpacing.md,
    paddingVertical: safeSpacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
  },
  trendCardLabel: {
    fontSize: 11,
    fontFamily: safeTypography.fonts.secondaryMedium,
    color: '#6B7280',
    fontWeight: safeTypography.weights.medium,
    textTransform: 'uppercase',
  },
  trendCardRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: safeSpacing.sm,
  },
  trendCardStatus: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: safeSpacing.xs,
  },
  trendCardIcon: {
    fontSize: 18,
    fontWeight: safeTypography.weights.bold,
  },
  trendCardStatusText: {
    fontSize: 14,
    fontFamily: safeTypography.fonts.primaryBold,
    color: '#d4c291',
    fontWeight: safeTypography.weights.bold,
  },
  trendCardBadge: {
    paddingHorizontal: safeSpacing.sm,
    paddingVertical: safeSpacing.xs / 2,
    borderRadius: 4,
    borderWidth: 1,
  },
  trendCardBadgeText: {
    fontSize: 12,
    fontFamily: safeTypography.fonts.primaryBold,
    fontWeight: safeTypography.weights.bold,
  },
});
